name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: tag
        run: |
          echo "tag_name=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

        # no need to pre-release yet
        #  if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+-[0-9]+$ ]]; then
        #    echo "pre_release=true" >> $GITHUB_OUTPUT
        #  fi

      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"
      - name: Update npm
        run: npm install -g npm@latest

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
          registry-url: "https://registry.npmjs.org"

      - run: bun install --frozen-lockfile
      # build + test
      - run: bun run prepublishOnly
      # pipe through xargs to remove whitespace
      - run: |
          FILE_NAME=$(bun pm pack --quiet | xargs)
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
      # https://github.com/oven-sh/bun/issues/15601 - provenance is not supported yet by bun :(
      - run: npm publish $FILE_NAME --provenance --ignore-scripts
      - run: gh release create ${{ steps.tag.outputs.tag_name }} $FILE_NAME --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
